<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 house1.glb --output house1.svelte --transform
Author: Cebrail Yıldız (https://sketchfab.com/cermo.gs.44)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/wooden-hut-low-8d916ce1494e4e2fad4387f9e73f999c
Title: wooden hut low
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import house1 from 'house1-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(house1, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Mesh
        geometry={gltf.nodes.wall2_Material003_0.geometry}
        material={gltf.materials['Material.003']}
        position={[-395.63, 11.26, 26.65]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[4.35, 72.76, 72.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.wall_Material001_0.geometry}
        material={gltf.materials['Material.001']}
        position={[-687.98, 11.26, -230.36]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-73.08, 73.08, 83.48]}
      />
      <T.Mesh
        geometry={gltf.nodes.wall3_Material007_0.geometry}
        material={gltf.materials['Material.007']}
        position={[-688.09, 11.26, 26.65]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[4.35, 72.76, 72.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.Roof_Material008_0.geometry}
        material={gltf.materials['Material.008']}
        position={[-541.9, 187.08, -97.12]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={73.08}
      />
      <T.Mesh
        geometry={gltf.nodes.Window_Material006_0.geometry}
        material={gltf.materials['Material.006']}
        position={[-395.53, 92.54, -29.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[4.35, 72.76, 72.38]}
      />
      <T.Mesh
        geometry={gltf.nodes.wall001_Material001_0.geometry}
        material={gltf.materials['Material.001']}
        position={[-688.2, 11.26, 26.54]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-73.08, 73.08, 75.46]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
