<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 rock2.glb --output rock2.svelte --transform
Author: anieldanjo (https://sketchfab.com/amir.danieldanjo)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/rock-17-free-rock-pack-vol3-2-4ac9f1f5375b438ba1ce0809720d83d7
Title: Rock_17_free_rock_pack_vol.3 (2)
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import rock2 from 'rock2-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(rock2, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.Rock_17} rotation={[-Math.PI / 2, 0, 0]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
