<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 rock3.glb --output rock3.svelte --transform
Author: Pedro Benítez (https://sketchfab.com/pedrobenitezx)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/rock-01-3cbb4cc6a35b43f595ca953c0ce36511
Title: Rock_01
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import rock3 from 'rock3-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(rock3, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_1.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_2.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_3.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_4.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_5.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_6.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_7.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_8.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_9.geometry} material={gltf.materials.tex_u1_v1} />
      <T.Mesh geometry={gltf.nodes.model_tex_u1_v1_0_10.geometry} material={gltf.materials.tex_u1_v1} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
