<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 rock2.glb --output rock2.svelte --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import rock2 from './rock2-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(rock2, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Rock_2.geometry} material={gltf.materials.Atlas} scale={100} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
