<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree4.glb --output tree4.svelte --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree4 from './tree4-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree4, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.treeFall_1.geometry} material={gltf.materials.foliageFall} />
    <T.Mesh geometry={gltf.nodes.treeFall_1_1.geometry} material={gltf.materials.rock} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
