<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree2.glb --output tree2.svelte --transform
Author: driggleman (https://sketchfab.com/driggleman)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/maple-tree-68bea58fd9a549a99cfa5d1c739c97a8
Title: Maple Tree
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree2 from 'tree2-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree2, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials['branch05.001']} />
      <T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials['mossybark02.001']} />
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['mossybark03.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
