<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree1.glb --output tree1.svelte --transform
Author: MaxLeburo (https://sketchfab.com/MaxLeburo)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/simple-tree-a3f4e00ecc384140a452abe91021aa0f
Title: Simple Tree
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree1 from 'tree1-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree1, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[6.84, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['stem.002']} />
      <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials['stem.001']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
