<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree1.glb --output tree1.svelte --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree1 from './tree1-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree1, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['Node-Mesh'].geometry} material={gltf.materials.mat9} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_1'].geometry} material={gltf.materials.mat20} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
