<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree4.glb --output tree4.svelte --transform
Author: Razzhivin_Ivan (https://sketchfab.com/Razzhivin_Ivan)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/birch-40fa24e8e5214716ae09cadd5d0e8181
Title: Birch
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree4 from 'tree4-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree4, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.trunk} />
    <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_11.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_13.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_15.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_16.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_17.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_19.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_21.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_22.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_26.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_27.geometry} material={gltf.materials.material} />
    <T.Mesh geometry={gltf.nodes.Object_29.geometry} material={gltf.materials.trunk} />
    <T.Mesh geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_31.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_32.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_33.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_34.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_35.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_36.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_37.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_38.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_39.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_40.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_41.geometry} material={gltf.materials.frond} />
    <T.Mesh geometry={gltf.nodes.Object_43.geometry} material={gltf.materials.trunk} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
