<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree5.glb --output tree5.svelte --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree5 from './tree5-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree5, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.PollardWillowTree_mesh.geometry} material={gltf.materials.PollardWillowTree_mat} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
