<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 island3.glb --output island3.svelte --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import island3 from './island3-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(island3, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['Island03_Cylinder-Mesh'].geometry} material={gltf.materials.Dirt} />
    <T.Mesh geometry={gltf.nodes['Island03_Cylinder-Mesh_1'].geometry} material={gltf.materials.Grass} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
