<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 tree2.glb --output tree2.svelte --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import tree2 from './tree2-transformed.glb'

  export const ref = new Group()

  const gltf = useGltf(tree2, { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.mesh1406566609.geometry} material={gltf.materials.mat20} />
    <T.Mesh geometry={gltf.nodes.mesh1406566609_1.geometry} material={gltf.materials.mat19} />
    <T.Mesh geometry={gltf.nodes.mesh1406566609_2.geometry} material={gltf.materials.mat10} />
    <T.Mesh geometry={gltf.nodes.mesh1406566609_3.geometry} material={gltf.materials.mat9} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
